### ISSUE TITLE
BatchRunnerMP raises pickle typeError

### ISSUE THREAD

**Issue by nathanvdlei** [projectmesa/mesa#787]
**Describe the bug**
Using the BatchRunnerMP.run_all() function results in a pickle TypeError:

> can't pickle dict_values objects

I suspect the bug is in the multiprocess module. Updating pickle, mesa, multiprocess dill etc did not solve the problem.

**Additional context**
Python 3.7.3
Working in jupyter notebook
OS: Windows 10
Intel Core i7-8565U Processor

Full stacktrace:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-2e9800f54d7c> in <module>
     15                       max_steps=500,
     16                       model_reporters=data_collector)
---> 17 batch.run_all()
     18 
     19 data = batch.get_model_vars_dataframe()

c:\users\natha\agent based modelling\notebooks\1. mesa introduction\src\mesa\mesa\batchrunner.py in run_all(self)
    378             results = []
    379             for task in job_queue:
--> 380                 for model_vars, agent_vars in list(task):
    381                     results.append((model_vars, agent_vars))
    382                 pbar.update()

~\Anaconda3\lib\site-packages\multiprocess\pool.py in next(self, timeout)
    746         if success:
    747             return value
--> 748         raise value
    749 
    750     __next__ = next                    # XXX

~\Anaconda3\lib\site-packages\multiprocess\pool.py in _handle_tasks(taskqueue, put, outqueue, pool, cache)
    429                         break
    430                     try:
--> 431                         put(task)
    432                     except Exception as e:
    433                         job, idx = task[:2]

~\Anaconda3\lib\site-packages\multiprocess\connection.py in send(self, obj)
    207         self._check_closed()
    208         self._check_writable()
--> 209         self._send_bytes(_ForkingPickler.dumps(obj))
    210 
    211     def recv_bytes(self, maxlength=None):

~\Anaconda3\lib\site-packages\multiprocess\reduction.py in dumps(cls, obj, protocol, *args, **kwds)
     52     def dumps(cls, obj, protocol=None, *args, **kwds):
     53         buf = io.BytesIO()
---> 54         cls(buf, protocol, *args, **kwds).dump(obj)
     55         return buf.getbuffer()
     56 

~\Anaconda3\lib\site-packages\dill\_dill.py in dump(self, obj)
    443             raise PicklingError(msg)
    444         else:
--> 445             StockPickler.dump(self, obj)
    446         stack.clear()  # clear record of 'recursion-sensitive' pickled objects
    447         return

~\Anaconda3\lib\pickle.py in dump(self, obj)
    435         if self.proto >= 4:
    436             self.framer.start_framing()
--> 437         self.save(obj)
    438         self.write(STOP)
    439         self.framer.end_framing()

~\Anaconda3\lib\pickle.py in save(self, obj, save_persistent_id)
    502         f = self.dispatch.get(t)
    503         if f is not None:
--> 504             f(self, obj) # Call unbound method with explicit self
    505             return
    506 

~\Anaconda3\lib\pickle.py in save_tuple(self, obj)
    784         write(MARK)
    785         for element in obj:
--> 786             save(element)
    787 
    788         if id(obj) in memo:

~\Anaconda3\lib\pickle.py in save(self, obj, save_persistent_id)
    502         f = self.dispatch.get(t)
    503         if f is not None:
--> 504             f(self, obj) # Call unbound method with explicit self
    505             return
    506 

~\Anaconda3\lib\pickle.py in save_tuple(self, obj)
    769         if n <= 3 and self.proto >= 2:
    770             for element in obj:
--> 771                 save(element)
    772             # Subtle.  Same as in the big comment below.
    773             if id(obj) in memo:

~\Anaconda3\lib\pickle.py in save(self, obj, save_persistent_id)
    502         f = self.dispatch.get(t)
    503         if f is not None:
--> 504             f(self, obj) # Call unbound method with explicit self
    505             return
    506 

~\Anaconda3\lib\pickle.py in save_tuple(self, obj)
    769         if n <= 3 and self.proto >= 2:
    770             for element in obj:
--> 771                 save(element)
    772             # Subtle.  Same as in the big comment below.
    773             if id(obj) in memo:

~\Anaconda3\lib\pickle.py in save(self, obj, save_persistent_id)
    522             reduce = getattr(obj, "__reduce_ex__", None)
    523             if reduce is not None:
--> 524                 rv = reduce(self.proto)
    525             else:
    526                 reduce = getattr(obj, "__reduce__", None)

TypeError: can't pickle dict_values objects

**Comment by dmasad** [comment]
It looks like for some reason `dict_values` (which get returned when you call `.values()` from a dictionary) aren't pickleable (and my understanding is that `multiprocessing` uses pickles to pass objects around). Is there anywhere in your code where you're assigning dictionary values to something? If so, try wrapping it in a `list` -- e.g. `my_var = list(my_dict.values())`

**Comment by nathanvdlei** [comment]
I do not believe that any of the parameter in our model cause the problems. We do not seem to implement any dictionaries, except for defining the DataCollector parameters. The problem seems to occur with the  `fixed_params` and `variable_params` and `model_reporters`,  which are arguments to `BatchRunnerMP` These three are all dictionaries. The 'trick' described of transforming to a list does not seem to work for these parameters, as `.items()` is used to acces their contents.

**Comment by bastiaanzwanenburg** [comment]
I'm struggling with a similar issue so I was wondering whether you were able to solve this, and if so, how?

**Comment by nathanvdlei** [comment]
If I remember correctly we managed to use the BatchRunnerMP on MacOS, but not on Windows

**Comment by tpike3** [comment]
I was having a similar problem and after I wrapped the dict values in the list I ran into some other issues, from what I can tell based on updates to multiprocessing. I have built a variation of BatchRunnerMP which prevents this issue. The challenge it is not development ready.  

In an effort to make it development ready I have attached it below.  If you are willing to try it then that will help ensure its functionality before integrating. The zip file contains 2 files bathrunner_local.py and datacollection.py. datacollection.py was necessary because the lambda function was also preventing multiprocessing. This variation allows lambda or pass the function and the parameters in an iterable like a list. An example of these scripts being employed is here https://github.com/snunezcr/COVID19-mesa if you would like to look at them.   


[Mesa-BatchRunnerMP Test.zip](https://github.com/projectmesa/mesa/files/4629011/Mesa-BatchRunnerMP.Test.zip)
 
If you do try it please let me know how it goes so I can continue to improve it.

**Comment by bastiaanzwanenburg** [comment]
Im on MacOS as well. And thanks @tpike3, I'll implement your tests into my code next week and will get back to you with the results.

**Comment by tpike3** [comment]
@bastiaanzwanenburg Great thanks! I know it works on Windows, am confident it will work on MacOS and Linux, but would like some other tests.

**Comment by BAFurtado** [comment]
> It looks like for some reason `dict_values` (which get returned when you call `.values()` from a dictionary) aren't pickleable (and my understanding is that `multiprocessing` uses pickles to pass objects around). Is there anywhere in your code where you're assigning dictionary values to something? If so, try wrapping it in a `list` -- e.g. `my_var = list(my_dict.values())`

Thanks @dmasad , I do have a dictionary of parameters that I use when I instantiate my model which is necessary to grab the correct data generation process. Do you think that might be it? When we are talking about a list of dict values, I can replace them. But how do I do it when I have to pass a dictionary of parameters? Here is the point: https://github.com/BAFurtado/home_violence/blob/b7e51b3875eacfbd0873af6c7d017ca732f601c9/violence/model.py#L84 Best,

**Comment by tpike3** [comment]
@BAFurtado your initiation with a params dictionary should be fine. The problem is in the BathRunnerMP module when it is making all the different parameter variations and then passing to the various processors is when the issues arises. So it is a line in the Mesa BatchRunner module that will give you an error. 

There are some different fixes, but right now it depends on your OS, as we look for a universal fix. 

Are you running on a Mac, Windows or Linux system?

**Comment by BAFurtado** [comment]
> @BAFurtado your initiation with a params dictionary should be fine. The problem is in the BathRunnerMP module when it is making all the different parameter variations and then passing to the various processors is when the issues arises. So it is a line in the Mesa BatchRunner module that will give you an error.
> 
> There are some different fixes, but right now it depends on your OS, as we look for a universal fix.
> 
> Are you running on a Mac, Windows or Linux system?

Oh, thank you very much to getting back to me. [this run was on a Windows server 2012 R2 server in which I do not have admin privileges]. At home/development I use a Linux Mint Tricia 19.3. Best,

**Comment by tpike3** [comment]
On Windows there are some challenges. But if you look at my comment 4 days ago there is a hyper link to a zip file with a batchrunner_local.py and datacollection.py. I also put a link to a Mesa based COVID model that uses those identical modules, so you can pull them from there is you like and see an example implementation.

Those modules will work on Windows, but no one has tried them on a Windows server as far as I know. The reasons for the datacollection.py, is you may need to remove your lambda functions from the reporters and that data collection version allows you to pass in the function an specific parameters if you need it.   

Happy for any feedback you have, as we try an get a universal BatchRunnerMP up and running. The code is a hot mess right, but it has worked on 2 different Windows based machines. 

Thank you, please advise any questions or concerns.

**Comment by BAFurtado** [comment]
Hi Tom. I'd try again today (I'm running 9200 iterations and I just accidentally closed PyCharm... but then, when I copied the two files it was going to overwrite the original datacollection... Is that it? Should I proceed?

**Comment by tpike3** [comment]
@BAFurtado personally I would not overwrite mesa's datacollection module, because it is not production ready. I recommend calling it something like datacollection2.py and the just updating your datacollection lines to use that module. In the end it is really based on your preference and how you manage your environments.

**Comment by jwalzberg** [comment]
Hi, 
Just wanted to share: 
-tpike3 fix worked for me but can't use batch_run.get_model_vars_dataframe() so I looked for another fix.
-Ended up installing Mesa version 0.8.6 instead of 0.8.7 and it worked fine!

**Comment by manentai** [comment]
> If I remember correctly we managed to use the BatchRunnerMP on MacOS, but not on Windows. My assumption is that the pickle error on Windows is OS specific. What OS are you using?

I am experiencing the same issue and I am on Mac OSX Catalina 10.15.5

**Comment by tpike3** [comment]
@jwalzberg What issue where you having with batch_run.get_model_vars_dataframe()?

**Comment by tpike3** [comment]
@manentai Python made some updates to multiprocessing that broke BatchRunnerMP. The Mesa fix is going through QA/QC and will hopefully be push in the next week or so. Did you try the code form the comments I posted up on May 14th?

**Comment by jwalzberg** [comment]
@tpike3 with the modified data collection and BatchRunnerMP from the Test.zip file, batch_run.get_model_vars_dataframe() return AttributeError: 'BatchRunnerMP' object has no attribute 'get_model_vars_dataframe' (which makes sense as the method is between quotes in the batch_runner file). Hence, I assigned batch_run.run_all() to a variable like in your covid-19 example (line 174 of the model_runne.py file) but ran into another issue: processes would not close, soon exhausting my memory. After fixing it by using Pool.terminate() I still could not figure an easy way to retrieve data from the variable that batch_run.run_all() was assigned to. Because the BatchRunnerMP was working fine on another computer I started looking at the difference in the python environment between the two machines instead (which was the Mesa version).

I have python 3.7 and downloaded the last version of pathos prior to run BatchRunnerMP. I am really wondering why BatchRunnerMP works in the 0.8.6 version of Mesa but not in 0.8.7. Using the 0.8.6 version also works on two of my computers: one with Windows7 and one with Windows10.

**Comment by tpike3** [comment]
@jwalzberg that is interesting with the various versions of Mesa I wonder if pathos made some updates as I know they were tracking some issues as well. The goal with the update is to make it system agnostic and so we tried it on multiple OSs but even after those tests it was a little hazy.

I will have to dig deeper into the processes not closing. Were you using an IDE like Spyder or PyCharm?

For the covid-19 example, yes I did block out "get_modelvars_dataframes()" and in that test code the BatchRunnerMP returned the models datacollector in a dictionary with the parameters as the key. (Sorry that probably needed to be more explicit.) This was identified in another issue in that the user could not get the agent data per step for each run. To try and get the best of both worlds the update allow  users to get either specific data from each run  by get a dictionary of the model datacollectors  or call batchrun data where users only get specific data from each run with "get_modelvars_dataframes()"

**Comment by jwalzberg** [comment]
Yes, I use PyCharm. Thanks for looking into the issue and developing a fix!

**Comment by manentai** [comment]
> @manentai Python made some updates to multiprocessing that broke BatchRunnerMP. The Mesa fix is going through QA/QC and will hopefully be push in the next week or so. Did you try the code form the comments I posted up on May 14th?

@tpike3 yes I am trying it right now, it seems that it's working fine, my simulations are running without errors so far... One thing, I have noticed that there is no indication of how many runs have passed nor any information about the time.

**Comment by tpike3** [comment]
@manentai Yes I added the pbar update in the BatchRunnerMP update so it will show the number if iterations

**Comment by Corvince** [comment]
Hopefully this is resolved now with #917. Install mesa with `pip install -e git+https://github.com/projectmesa/mesa#egg=mesa` to retrieve the latest version or wait for the 0.8.8 release.

Anyone please feel free to re-open if there are any remaining issues

**Comment by digitaldust** [comment]
Hi, I can see that now I don't have pickle errors and that the count of runs is displayed, but after 340 runs (around 4mins) my kernel invariably dies... if I use @tpike3 old solution, I am able to finish the runs and collect results.. am I the only one experiencing this problem?
unfortunately the terminal does not show any error...

**Comment by tpike3** [comment]
@digitaldust Try running BatchRunnerMP with the Keyword Argument ```nr_processes=1```. One challenge with multi-processing is if the processor that errors is not the the processor with the output then you won't see the traceback. This will keep it on one processor so we can see the traceback. 

Please let me know what you find so we can fix the issue, thanks!

**Comment by digitaldust** [comment]
@tpike3 I have tried with `nr_processes=1` but I had no output, just the kernel died without any apparent reasons... I can say however that with only one process the progress bar is not active nor displayed - just reporting this, it's probably an intended behavior...

**Comment by digitaldust** [comment]
@tpike3 I have now tried many times with `n_process=1` and it's odd, sometimes it fails, sometimes it doesnt. But it always fails when `n_processes>1`... I'll keep you posted...

**Comment by jackiekazil** [comment]
We should really create a debug mode for Mesa. __
Debug=True  and then everything gets logged.

**Comment by jackiekazil** [comment]
We should really create a debug mode for Mesa. __
Debug=True  and then everything gets logged.

**Comment by tpike3** [comment]
@digitaldust Dang, those multiprocessing problems where there is hang and no traceback are always difficult. Standing by if there is anything I can do to assist. 

@jackiekazil concur
